version: '3'
services:
    postgres:
        image: 'postgres'
        ports: 
            - "5432:5432"
        expose:
            - "5432"
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=12345
        - POSTGRES_DB=postgres
    my-java:
        build: .
        ports:
            - "1010:1010"